services:
    php:
        build:
            dockerfile: docker/dev/php/Dockerfile
        volumes:
            -   ./backend/:/application
        working_dir: /application
        depends_on:
            -   postgres
            -   redis

    redis:
        image: eqalpha/keydb:alpine_x86_64_v6.3.4
        volumes:
            -   redis_data:/data
        ports:
            - "6379:6379"

    nginx:
        ports:
            - "8000:80"
        volumes:
            - ./docker/dev/nginx/flex-server.conf:/etc/nginx/conf.d/default.conf
            - ./backend/public:/application/public
        image: nginx:1.25.5-alpine
        depends_on:
            -   php
            -   node

    postgres:
        image: postgres:16.2-alpine
        environment:
            POSTGRES_DB: flex_server
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            -   "5432:5432"

    node:
        image: node:21-alpine
        volumes:
            -  ./frontend:/application
        working_dir: /application
        ports:
            -   8001:5173
        command: ["npm", "run", "dev"]


volumes:
    postgres_data: {}
    redis_data: {}
